alternate: Crystal's Note
font:
  logo:
    external: true
    family: Nova Slim
    size: 3.5
darkmode: true
loader:
  start: false 
  switch: false
fireworks:
  enable: true # 是否启用
  color: # 烟花颜色
    - "rgba(70, 93, 141,.9)"
    - "rgba(94, 120, 170,.9)"
    - "rgba(118, 147, 198,.9)"
    - "rgba(142, 174, 227,.9)"
    - "rgba(166, 200, 255,.9)"
    - "rgba(183, 186, 241,.9)"
menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  # links: /links/ || magic

social:
  github: https://github.com/x200706 || github || "#ffffff"
  mastodon: https://liker.social/@chi200706 || person || "#ffffff"

sidebar:
  # Sidebar Position.
  position: left
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: fan.png
widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论
leancloud_visitors:
  enable: false
valine:
  appId: sXmMHyiITZk5sRXNXGWkkvFA-MdYXbMMI
  appKey: BlbX0DIYKZ9EjUiMv3raoowa
  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-TW
  visitor: true # 文章访问量统计
  comment_count: true
  NoRecordIP: false # 不记录 IP
  serverURLs: https://sxmmhyii.api.lncldglobal.com
  powerMode: true # 默认打开评论框输入特效
  avatarCDN: https://cdn.v2ex.com/gravatar/
  avatarUrl: https://cdn.v2ex.com/gravatar/
  tagMeta:
    visitor: 訪客
    master: 站長
    friend: 友列
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
  tagMember:
    master:
      - 1d491b58d30e35ade2a5e6272e5ffbf8
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
# image_server: "https://source.unsplash.com/1600x900/?snow"
reward:
  # If true, reward will be displayed in every article by default.
  enable: false
# audio:
#   - 